### PR TITLE
Fix RFF import

### LINKED ISSUE #413: Update Trieste to use latest gpflux
**Describe the feature you'd like**
Update Trieste to use `gpflux 0.2.7+`

**Is your feature request related to a problem? Please describe.**
Trieste currently only works with `gpflux>=0.2.0, <0.2.4`.  Using the latest version (0.2.7) initally breaks because of a refactoring within `gpflux`.  i.e. running `pytest tests` results in: 
```
trieste/acquisition/sampler.py:26: in <module>
    from gpflux.layers.basis_functions import RandomFourierFeatures
E   ImportError: cannot import name 'RandomFourierFeatures' from 'gpflux.layers.basis_functions'
```

which should be updated to:
```from gpflux.layers.basis_functions.fourier_features.random import RandomFourierFeatures```

After doing so, further errors appear in the tests.

**Describe alternatives you've considered**
Temporarily pinned Trieste to `gpflux 0.2.3`, the last gpflux release that it works with.

**Additional context**
Once this is done, we might also want to consider how me make sure only a compatible version of gpflux is picked up in future.

### PR DESCRIPTION
**Pull request by vpicheny**
This PR changes the import of gpflux RandomFourierFeatures.

### CODE REVIEW

**Review by hstojic — APPROVED** [review]
looks good

**Comment by hstojic** [comment]
@tensorlicious noted errors when trying to upgrade to the newest version of GPflux, see #413

**Comment by hstojic** [comment]
@avullo it seems like PR is ready, can you please run full docs build and tests locally? 
recently we switched to a quick version before merging the PR and full ones run after merging into develop as they are really slow, so GH actions check here is not fully informative for merging in - since this is changing a dependency version I suspect some tests or docs might still fail at the end

**Comment by avullo** [comment]
> @avullo it seems like PR is ready, can you please run full docs build and tests locally? recently we switched to a quick version before merging the PR and full ones run after merging into develop as they are really slow, so GH actions check here is not fully informative for merging in - since this is changing a dependency version I suspect some tests or docs might still fail at the end

@hstojic I've run a full docs build and it seems ok, good to go IMHO.

**Comment by hstojic** [comment]
@avullo thanks for chipping in with this, merging in!
