### ISSUE TITLE
Update Trieste to use latest gpflux

### ISSUE THREAD

**Issue by tensorlicious** [secondmind-labs/trieste#413]
**Describe the feature you'd like**
Update Trieste to use `gpflux 0.2.7+`

**Is your feature request related to a problem? Please describe.**
Trieste currently only works with `gpflux>=0.2.0, <0.2.4`.  Using the latest version (0.2.7) initally breaks because of a refactoring within `gpflux`.  i.e. running `pytest tests` results in: 
```
trieste/acquisition/sampler.py:26: in <module>
    from gpflux.layers.basis_functions import RandomFourierFeatures
E   ImportError: cannot import name 'RandomFourierFeatures' from 'gpflux.layers.basis_functions'
```

which should be updated to:
```from gpflux.layers.basis_functions.fourier_features.random import RandomFourierFeatures```

After doing so, further errors appear in the tests.

**Describe alternatives you've considered**
Temporarily pinned Trieste to `gpflux 0.2.3`, the last gpflux release that it works with.

**Additional context**
Once this is done, we might also want to consider how me make sure only a compatible version of gpflux is picked up in future.
